version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak-x:12.0.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=DEBUG
    restart: always
    volumes:
      - ./create-sirix-users.sh:/opt/jboss/startup-scripts/create-sirix-users.sh
    command:
      - "start-dev"
  server:
    image: sirixdb/sirix
    ports:
      - 9443:9443
    restart: always
    volumes:
      - /opt/sirix/sirix-data:/opt/sirix/sirix-data
      - ./sirix-conf.json:/opt/sirix/sirix-conf.json
